config/routes.rb
Rails.application.routes.draw do
  resources :store_cars
  resources :cars
  resources :stores
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
	validates :name, presence: true, uniqueness: true  
	has_many :stores, :through => :store_cars  
	has_many :store_cars, :dependent => :destroy
end

app/models/store.rb
class Store < ApplicationRecord
	has_many :cars, :through => :store_cars  
	has_many :store_cars, :dependent => :destroy
end

app/models/store_car.rb
class StoreCar < ApplicationRecord
	validates_uniqueness_of :car_id, :scope => [:store_id]  
  belongs_to :store
  belongs_to :car
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:name)
    end
end

app/controllers/store_cars_controller.rb
class StoreCarsController < ApplicationController
  before_action :set_store_car, only: [:show, :edit, :update, :destroy]

  # GET /store_cars
  # GET /store_cars.json
  def index
    @store_cars = StoreCar.all
  end

  # GET /store_cars/1
  # GET /store_cars/1.json
  def show
  end

  # GET /store_cars/new
  def new
    @store_car = StoreCar.new
  end

  # GET /store_cars/1/edit
  def edit
  end

  # POST /store_cars
  # POST /store_cars.json
  def create
    @store_car = StoreCar.new(store_car_params)

    respond_to do |format|
      if @store_car.save
        format.html { redirect_to @store_car, notice: 'Store car was successfully created.' }
        format.json { render :show, status: :created, location: @store_car }
      else
        format.html { render :new }
        format.json { render json: @store_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /store_cars/1
  # PATCH/PUT /store_cars/1.json
  def update
    respond_to do |format|
      if @store_car.update(store_car_params)
        format.html { redirect_to @store_car, notice: 'Store car was successfully updated.' }
        format.json { render :show, status: :ok, location: @store_car }
      else
        format.html { render :edit }
        format.json { render json: @store_car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /store_cars/1
  # DELETE /store_cars/1.json
  def destroy
    @store_car.destroy
    respond_to do |format|
      format.html { redirect_to store_cars_url, notice: 'Store car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store_car
      @store_car = StoreCar.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_car_params
      params.require(:store_car).permit(:store_id, :car_id)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/store_cars_helper.rb
module StoreCarsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.name %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @car.name %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/store_cars/_form.html.erb
<%= form_with(model: store_car, local: true) do |form| %>
  <% if store_car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store_car.errors.count, "error") %> prohibited this store_car from being saved:</h2>

      <ul>
      <% store_car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :store_id %>
    <%= form.collection_select(:store_id, Store.all, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :car_id %>
    <%= form.collection_select(:car_id, Car.all, :id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/store_cars/edit.html.erb
<h1>Editing Store Car</h1>

<%= render 'form', store_car: @store_car %>

<%= link_to 'Show', @store_car %> |
<%= link_to 'Back', store_cars_path %>

app/views/store_cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Store Cars</h1>

<table>
  <thead>
    <tr>
      <th>Store</th>
      <th>Car</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @store_cars.each do |store_car| %>
      <tr>
        <td><%= store_car.store.name %></td>
        <td><%= store_car.car.name %></td>
        <td><%= link_to 'Show', store_car %></td>
        <td><%= link_to 'Edit', edit_store_car_path(store_car) %></td>
        <td><%= link_to 'Destroy', store_car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store Car', new_store_car_path %>

app/views/store_cars/new.html.erb
<h1>New Store Car</h1>

<%= render 'form', store_car: @store_car %>

<%= link_to 'Back', store_cars_path %>

app/views/store_cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Store:</strong>
  <%= @store_car.store.name %>
</p>

<p>
  <strong>Car:</strong>
  <%= @store_car.car.name %>
</p>

<%= link_to 'Edit', edit_store_car_path(@store_car) %> |
<%= link_to 'Back', store_cars_path %>

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>